# Этапы
stages:
  - build
  - sast
  - dast
  - sca

# Test
build_app:
  stage: build
  tags:
    - docker
  script:
    - echo "Building project..."  

# SAST
security-check-sast:
  stage: sast
  image: returntocorp/semgrep
  tags:
  - docker
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  allow_failure: true
  script:
    - semgrep --config auto --output scan_results-sast.json --json .
    - ls -la
  artifacts:
    when: always
    name: "$CI_JOB_STAGE-scan_results-sast.json"
    paths:
      - scan_results-sast.json



# DAST
security-check-dast:
  stage: dast
  tags:
  - docker
  image:
    name: ghcr.io/zaproxy/zaproxy:stable
    entrypoint: [""]
  before_script:
    - mkdir -p /zap/wrk
  script:
    - python3 /zap/zap-baseline.py -t http://192.168.1.1:8080 -I -r scan_results-dast.html
    - ls -la /zap/wrk
  artifacts:
    when: always
    name: "$CI_JOB_STAGE-scan_results-dast.html"
    paths:
      - /zap/wrk/scan_results-dast.html

#SCA
security-check-sca:
  stage: sca
  tags:
    - custom
  image: 
    name: aquasec/trivy:latest
    entrypoint: [""] 
  script:
    - trivy image flink:1.16-java8 -o scan_results-sca.json
    - ls -la 
  artifacts:
    when: always
    name: "$CI_JOB_STAGE-scan_results-sca.json"
    paths:
      - scan_results-sca.json
  